### ISSUE TITLE
ImportError: ImportError: cannot import name 'hmm' from 'boostnano'

### ISSUE THREAD

**Issue by yefei521** [haotianteng/BoostNano#2]
Hi
   After installing Boostnano exporting PATH into Python path, and all of requirements has been installed, I met such trouble when using command : **python ~/biosoft/BoostNano/boostnano/boostnano_eval.py -i fast5_pass/ -o 02BoostNano/ -m ~/biosoft/BoostNano/model/** 

**Traceback (most recent call last):
  File "/apps/users/yefei/biosoft/BoostNano/boostnano/boostnano_eval.py", line 8, in <module>
    from boostnano.boostnano_model import CSM
ImportError: No module named boostnano.boostnano_model**

Check the folder in BoostNano/model/, indeed, there was no file named **boostnano.boostnano_model**

What's more, **Check out the sample code in the Jupyter Notebook Sample.ipynb for how to use the package.** in REANDME, however, I can open the file--Sample.ipynb, but  have no idea of it, could you please tell me how to use BoostNano with more detail ? 

Thanks very much

**Comment by haotianteng** [comment]
Sample.ipynb is a Jupyter Notebook file, open it with Jupyter Notebook. 

Export the path where you installed BoostNano into PYTHONPATH, that is, change the "PATH_TO_BOOSTNANO" with your own path of Boostnano.

I have no problem running the code on my end.
